newPlan = "//span[@class='ng-star-inserted'][normalize-space()='Planos']"
Plan = "plano"
messageMonth = "qtdMensagem"
interval = "intervalo"
monthlyInterval = "Mensal"
intervalAnnual = "Anual"
price = "preco"
paymentMethod = "formaPagamento"
askCustomer = "Pergunte ao cliente"
BankSlipPix = "Boleto/PIX"
visibleId = "visivel"
visibleYes = "Sim"
VisibleNo = "Não"
